package com.renanpalmeira.hibernate;


import java.util.Date;

/**
 * Member generated by hbm2java
 */
public class Member  implements java.io.Serializable {


     private Integer idMember;
     private String name;
     private String email;
     private String avatar;
     private int idMemberPhone;
     private Date createDate;
     private Date updateDate;
     private int status;

    public Member() {
    }

	
    public Member(String name, String email, int idMemberPhone, Date createDate, Date updateDate, int status) {
        this.name = name;
        this.email = email;
        this.idMemberPhone = idMemberPhone;
        this.createDate = createDate;
        this.updateDate = updateDate;
        this.status = status;
    }
    public Member(String name, String email, String avatar, int idMemberPhone, Date createDate, Date updateDate, int status) {
       this.name = name;
       this.email = email;
       this.avatar = avatar;
       this.idMemberPhone = idMemberPhone;
       this.createDate = createDate;
       this.updateDate = updateDate;
       this.status = status;
    }
   
    public Integer getIdMember() {
        return this.idMember;
    }
    
    public void setIdMember(Integer idMember) {
        this.idMember = idMember;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public String getAvatar() {
        return this.avatar;
    }
    
    public void setAvatar(String avatar) {
        this.avatar = avatar;
    }
    public int getIdMemberPhone() {
        return this.idMemberPhone;
    }
    
    public void setIdMemberPhone(int idMemberPhone) {
        this.idMemberPhone = idMemberPhone;
    }
    public Date getCreateDate() {
        return this.createDate;
    }
    
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }
    public Date getUpdateDate() {
        return this.updateDate;
    }
    
    public void setUpdateDate(Date updateDate) {
        this.updateDate = updateDate;
    }
    public int getStatus() {
        return this.status;
    }
    
    public void setStatus(int status) {
        this.status = status;
    }




}


